### ISSUE TITLE
Setting up solargraph with nvim-lsp not working

### ISSUE THREAD

**Issue by Yathi** [neovim/nvim-lspconfig#387]
**Nvim version:**
```bash
NVIM v0.5.0-nightly
Build type: Release
LuaJIT 2.0.5
```

**init.vim:**
```
call plug#begin('~/.vim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'vim-ruby/vim-ruby'
Plug 'neovim/nvim-lsp'
Plug 'neovim/nvim-lspconfig'
Plug 'tpope/vim-rails'
call plug#end()

lua require'nvim_lsp'.tsserver.setup{}
lua require'nvim_lsp'.solargraph.setup{}
```

**checkhealth response**:
```

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    - $ nvim
    - $ cat /tmp/log_{PID}
    - and then create an issue on github

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: solargraph: configuration checked.
  - INFO: tsserver: configuration checked.

health#nvim_lsp#check
========================================================================
## Checking language server protocol configuration
  - INFO: solargraph: configuration checked.
  - INFO: tsserver: configuration checked.

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help |provider-python|
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Python version: 3.8.5
  - INFO: pynvim version: 0.4.2
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
  - INFO: Host: /Users/yathi/.rbenv/shims/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.8.1

## Node.js provider (optional)
  - INFO: Node.js: v10.15.3
  - INFO: Nvim node.js host: /usr/local/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.9.0

## Perl provider (optional)
  - ERROR: perl provider error:
    - ADVICE:
      - Perl version is too old, 5.22+ required

```

But when I open a .rb file and run `:lua print(vim.inspect(vim.lsp.buf_get_clients()))` I just get `{}` as the response. 

It seems to work fine for `ts` files and the lua print returns non empty result. This may not be a LSP issue and maybe an issue with my setup or solargraph, but I would love any help. Thank you!

**Comment by bowmanmike** [comment]
Same problem here. LSP is working fine for Elixir and Python, but `solargraph` isn't being picked up for some reason.

**Comment by Scupake** [comment]
Same, LSP works with Lua, but it doesn't with Ruby

**Comment by teto** [comment]
you can check out the lsp log from the file `:lua print(vim.lsp.log.get_filename())`

**Comment by wingpin6** [comment]
Late comment, but https://github.com/neovim/nvim-lspconfig/pull/37#issuecomment-670666514 solved my problem.

Perhaps this should be in the README for "default" solargraph config?
I have noticed in the logs that solargraph start is logged through stderr if that's not intentional.

```
[ ERROR ] 2020-11-23T19:18:30-0500 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:443 ]    "rpc"   "solargraph"    "stderr"        "Solargraph is listening on stdio PID=1692\n"                    
[ ERROR ] 2020-11-23T19:18:32-0500 ] /usr/local/share/nvim/runtime/lua/vim/lsp/rpc.lua:443 ]    "rpc"   "solargraph"    "stderr"        "[ANY] Solargraph initialized (1.0088329000000158 seconds)\n" 
```

**Comment by kassio** [comment]
I'm with the same problem.

> you can check out the lsp log from the file :lua print(vim.lsp.log.get_filename())

I tried that, but it returns:

```
E5108: Error executing lua [string ":lua"]:1: attempt to index field 'log' (a nil value)
```
---
> Late comment, but #37 (comment) solved my problem

I tried this config as well, but still doesn't work. 😢 

---
> But when I open a .rb file and run :lua print(vim.inspect(vim.lsp.buf_get_clients())) I just get {} as the response

This is exactly what's happening for me.

---
I added a function to _log_ when a LSP gets attached, and it's working for my other LSPs (lua and json), but not for ruby:

```lua
local lspconfig = require'lspconfig'

local function attacher(client)
  print('Attaching LSP: ' .. client.name)
end

lspconfig.jsonls.setup{
  on_attach = attacher
}

lspconfig.solargraph.setup{
  settings = {
    solargraph = {
      command = '/Users/kassioborges/.asdf/shims/solargraph',
      diagnostics = true,
      completion = true
    }
  },

  on_attach = attacher
}
```

**Comment by kassio** [comment]
Sharing as this might help other people.

This is very new to me, tailing the log (`lua print(vim.lsp.get_log_path())` to get the path of the log) when I open a ruby file I get:

```
[ ERROR ] 2020-12-03T17:58:38+0000 ] ...ovim/HEAD-fa73bb7/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"solargraph"	"stderr"	"Solargraph is listening on stdio PID=96643\n"
[ ERROR ] 2020-12-03T17:59:42+0000 ] ...ovim/HEAD-fa73bb7/share/nvim/runtime/lua/vim/lsp/rpc.lua:455 ]	"rpc"	"solargraph"	"stderr"	"[WARN] Yardoc at /Users/kassioborges/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/doc/google-api-client-0.33.2/.yardoc is too large to process (159089201 bytes)\n"
```

So, the problems seems to be that my project is too big to solargraph. 😞 

I tested on a smaller project and it worked. 🎉

**Comment by mjlbach** [comment]
@Yathi  Is this issue filed upstream with solargraph? It doesn't seem to be a nvim-lspconfig specific problem. Can we close?

**Comment by mjlbach** [comment]
I'm almost certain that this has to do with the root pattern or an install issue. I updated the Readme to more explicitly cover root patterns, and updated install instructions in #556, as well as enabled diagnostics by default.

For solargraph to launch, you have to trigger the root pattern, which means your file has to be in a directory or subdirectory of a file containing either `.git` or `Gemfile` See here:  https://github.com/neovim/nvim-lspconfig/blob/42a13e5ad99b688bc7376fa4d236e924985d04cc/lua/lspconfig/solargraph.lua#L12. 

Feel free to reopen or reach out to me on Gitter if you're still having issues.

**Comment by adonespitogo** [comment]
Hi, I'm still experiencing this issue on Mac OS 12.6. But it works on my other machine which is running Ubuntu 22.04.

**Comment by mPanasiewicz** [comment]
> Hi, I'm still experiencing this issue on Mac OS 12.6. But it works on my other machine which is running Ubuntu 22.04.
> 
> ```
> NVIM v0.7.2
> Build type: Release
> LuaJIT 2.1.0-beta3
> Compiled by brew@Montere
> ```
> 
> UPDATE:
> 
> I have solved my problem. It was caused by a mismatched version of my Project ruby where I run `nvim` and the default ruby version of my rvm. So, I just had to `rvm --default use [my project ruby version]` and reinstall solargraph.

Same issue, I've installed solargraph through `Mason` but it didn't work. After manual installation everything backed to normal ;-)
